
package net.macrosigma.ws.regciv;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccesoBSGService", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", wsdlLocation = "https://www.bsg.gob.ec/sw/STI/BSGSW08_Acceder_BSG?wsdl")
public class AccesoBSGService
    extends Service
{

    private final static URL ACCESOBSGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.macrosigma.ws.regciv.AccesoBSGService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.macrosigma.ws.regciv.AccesoBSGService.class.getResource(".");
            url = new URL(baseUrl, "https://www.bsg.gob.ec/sw/STI/BSGSW08_Acceder_BSG?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://www.bsg.gob.ec/sw/STI/BSGSW08_Acceder_BSG?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCESOBSGSERVICE_WSDL_LOCATION = url;
    }

    public AccesoBSGService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccesoBSGService() {
        super(ACCESOBSGSERVICE_WSDL_LOCATION, new QName("http://bsg.gob.ec/AccesoBSGService", "AccesoBSGService"));
    }

    /**
     * 
     * @return
     *     returns BSG04AccederBSG
     */
    @WebEndpoint(name = "BSG04_Acceder_BSGPort")
    public BSG04AccederBSG getBSG04AccederBSGPort() {
        return super.getPort(new QName("http://bsg.gob.ec/AccesoBSGService", "BSG04_Acceder_BSGPort"), BSG04AccederBSG.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSG04AccederBSG
     */
    @WebEndpoint(name = "BSG04_Acceder_BSGPort")
    public BSG04AccederBSG getBSG04AccederBSGPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bsg.gob.ec/AccesoBSGService", "BSG04_Acceder_BSGPort"), BSG04AccederBSG.class, features);
    }

}
