
package net.macrosigma.ws.regciv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BSG04_Acceder_BSG", targetNamespace = "http://bsg.gob.ec/AccesoBSGService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BSG04AccederBSG {


    /**
     * 
     * @param validarPermisoPeticion
     * @return
     *     returns ec.gob.mtop.puertos.ws.acceso.ValidarPermisoRespuesta
     */
    @WebMethod(operationName = "ValidarPermiso")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ValidarPermiso", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "ec.gob.mtop.puertos.ws.acceso.ValidarPermiso")
    @ResponseWrapper(localName = "ValidarPermisoResponse", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "ec.gob.mtop.puertos.ws.acceso.ValidarPermisoResponse")
    public ValidarPermisoRespuesta validarPermiso(
        @WebParam(name = "ValidarPermisoPeticion", targetNamespace = "")
        ValidarPermisoPeticion validarPermisoPeticion);

}
