
package net.macrosigma.ws.regciv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSRegistroCivilConsultaCedula", targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula", wsdlLocation = "https://www.bsg.gob.ec/sw/RC/BSGSW01_Consultar_Cedula?wsdl")
public class WSRegistroCivilConsultaCedula_Service
    extends Service
{

    private final static URL WSREGISTROCIVILCONSULTACEDULA_WSDL_LOCATION;
    private final static WebServiceException WSREGISTROCIVILCONSULTACEDULA_EXCEPTION;
    private final static QName WSREGISTROCIVILCONSULTACEDULA_QNAME = new QName("http://www.registrocivil.gob.ec/ConsultaCedula", "WSRegistroCivilConsultaCedula");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.bsg.gob.ec/sw/RC/BSGSW01_Consultar_Cedula?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSREGISTROCIVILCONSULTACEDULA_WSDL_LOCATION = url;
        WSREGISTROCIVILCONSULTACEDULA_EXCEPTION = e;
    }

    public WSRegistroCivilConsultaCedula_Service() {
        super(__getWsdlLocation(), WSREGISTROCIVILCONSULTACEDULA_QNAME);
    }

    public WSRegistroCivilConsultaCedula_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSREGISTROCIVILCONSULTACEDULA_QNAME, features);
    }

    public WSRegistroCivilConsultaCedula_Service(URL wsdlLocation) {
        super(wsdlLocation, WSREGISTROCIVILCONSULTACEDULA_QNAME);
    }

    public WSRegistroCivilConsultaCedula_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSREGISTROCIVILCONSULTACEDULA_QNAME, features);
    }

    public WSRegistroCivilConsultaCedula_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSRegistroCivilConsultaCedula_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSRegistroCivilConsultaCedula
     */
    @WebEndpoint(name = "WSRegistroCivilConsultaCedulaPort")
    public WSRegistroCivilConsultaCedula getWSRegistroCivilConsultaCedulaPort() {
        return super.getPort(new QName("http://www.registrocivil.gob.ec/ConsultaCedula", "WSRegistroCivilConsultaCedulaPort"), WSRegistroCivilConsultaCedula.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSRegistroCivilConsultaCedula
     */
    @WebEndpoint(name = "WSRegistroCivilConsultaCedulaPort")
    public WSRegistroCivilConsultaCedula getWSRegistroCivilConsultaCedulaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.registrocivil.gob.ec/ConsultaCedula", "WSRegistroCivilConsultaCedulaPort"), WSRegistroCivilConsultaCedula.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSREGISTROCIVILCONSULTACEDULA_EXCEPTION!= null) {
            throw WSREGISTROCIVILCONSULTACEDULA_EXCEPTION;
        }
        return WSREGISTROCIVILCONSULTACEDULA_WSDL_LOCATION;
    }

}
