package net.macrosigma.ws.regciv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebService(name = "WSRegistroCivilConsultaCedula", targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula")
public interface WSRegistroCivilConsultaCedula {

 
    @WebMethod(operationName = "BusquedaPorCedula")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusquedaPorCedula", targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula", className = "net.macrosigma.ws.regciv.BusquedaPorCedula")
    @ResponseWrapper(localName = "BusquedaPorCedulaResponse", targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula", className = "net.macrosigma.ws.regciv.BusquedaPorCedulaResponse")
    public Cedula busquedaPorCedula(@WebParam(name = "Cedula", targetNamespace = "") String cedula, @WebParam(name = "Usuario", targetNamespace = "") String usuario, @WebParam(name = "Contrasenia", targetNamespace = "") String contrasenia);

    @WebMethod(operationName = "WsUp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WsUp", targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula", className = "net.macrosigma.ws.regciv.WsUp")
    @ResponseWrapper(localName = "WsUpResponse", targetNamespace = "http://www.registrocivil.gob.ec/ConsultaCedula", className = "net.macrosigma.ws.regciv.WsUpResponse")
    public Cedula wsUp();

}
